### ISSUE TITLE
온보딩 화면 1단계 기능 수정 및 구현

### ISSUE THREAD

**Issue by huiwoo-jo** [TeamDMU/DMU-Android#136]
## 🤔 목적

> 온보딩 수정본을 기반으로 1단계 학과 선택 화면의 기능을 수정 및 구현

## 📝 TO-DO

- [ ] 검색 기능
- [ ] 검색에 따른 리사이클러뷰 아이템 출력
- [ ] 학과 선택 시 검색창에 텍스트 출력 및 검색창 색상 변경
- [ ] 학과 선택 시 다음 버튼 활성화

**Comment by huiwoo-jo** [comment]
관련 이슈 #134
