### ISSUE TITLE
식단 코드 리팩토링 / 리디자인

### ISSUE THREAD

**Issue by huiwoo-jo** [TeamDMU/DMU-Android#176]
## 🤔 목적

> 식단 화면 코드 리팩토링 및 리디자인

## 📝 TO-DO

- [x] `CafeteriaFragment`의 `stu` 약자 변경 : https://github.com/TeamDMU/DMU-Android/pull/172#discussion_r1501471165
- [x] `Cafeteria.kt`의 `menu` 복수형 변경 : https://github.com/TeamDMU/DMU-Android/pull/172#discussion_r1503596575 -> resolved #158 
- [x] 식단 화면의 날짜 선택 부분이 슬라이더 형식으로 구현되어있음 날짜 선택부를 5일로 고정
- [x] 아이콘 여백 조정
- [x] 한식, 일품 크기 수정
- [x] 아이콘과 글씨 간격 수정 : 8dp
- [x] 한식, 일품 `View` 그림자 제거 & Stroke로 변경
