### ISSUE TITLE
온보딩 스텝 데이터 바인딩 제거

### ISSUE THREAD

**Issue by huiwoo-jo** [TeamDMU/DMU-Android#179]
## 🤔 목적

> 온보딩 스텝 부분의 데이터 바인딩 제거 및 온보딩 화면들 적용

## 📝 TO-DO

- [x] 온보딩 스텝 데이터 바인딩 제거
- [x] 온보딩 1단계 : 학과 선택 데이터 바인딩 제거
- [x] 온보딩 2단계 : 키워드 선택 데이터 바인딩 제거
- [x] 온보딩 3단계 : 알림 설정 데이터 바인딩 제거
