### ISSUE TITLE
1차 QA 반영

### ISSUE THREAD

**Issue by m6z1** [TeamDMU/DMU-Android#224]
## 🤔 목적

> 1차 QA 반영

## 📝 TO-DO

- [x] 검색 결과 없을 때 화면 추가
- [x] 두 글자 이상일 때 추가하란 디자인 반영
- [ ] 검색 빈 배경화면 선택 시 키보드 내리기
- [x] 스플래시 아이콘 키우기
