### ISSUE TITLE
2차 QA 반영

### ISSUE THREAD

**Issue by huiwoo-jo** [TeamDMU/DMU-Android#230]
## 🤔 목적

> 2차 QA 반영

## 📝 TO-DO

- [x] 온보딩 학과 검색 시 글자가 있을 때만 `X` 아이콘 활성화
- [x] 온보딩 키워드 / 설정 키워드 `chip`의 `ripple` 효과 제거
- [x] 식단 화면 날짜 표기 방식 수정 `01` -> `1`
- [x] 식단 화면의 날짜 표기 잘림
- [x] 권한 설정 `Tiramisu` 이전 버전
- [ ] 일품 메뉴 리스트 넣기
